### ISSUE TITLE
Reactive properties seems doesn't work

### ISSUE THREAD

**Issue by akasob** [Neroware/GodotRx#22]
Hello!
Your framework is just wonderful.
However, I found a problem. I need ReactiveProperty for my project, but it looks like even the example from the readme doesn't work as intended.

Steps to reproduce:
1. Make new project.
2. Download and enable plugin.
3. Create test scene based on Control.
4. Add script and place this code (from readme):

`var _hp : int = 100`
`var _stamina : float = 1.0`
`var _attack_damage : int = 100`

`func _ready():`
`	# Create ReactiveProperty from member`
`	var _Hp : ReactiveProperty = ReactiveProperty.FromMember(self, "_hp")`
`	var __ = _Hp.subscribe(func(i): print("Changed Hp ", i))`
`	_Hp.Value += 10`
`	print("Reflected: ", self._hp)` 
I expect "Reflected: 110" but _hp still contains 100
It needs fix or I misunderstand?

Thank you in advance for your help!

**Comment by Neroware** [comment]
G'Day and thank you for your heads-up on this! You are absolutely correct. 
This bug originates from disposables now disposing themselves when going out of scope. The behavior was correct on the 4.1-branch (This shows, why a test-suit would be important...)

I will fix this as soon as possible :)

**Comment by Neroware** [comment]
Fixed bug and verified behavior in 954a40f45fbad29a9b760678979d1a019722bd00
