### ISSUE TITLE
How to emit a new value

### ISSUE THREAD

**Issue by Arielmann** [Neroware/GodotRx#23]
This might be common knowledge with people using Reactive programming paradigm, but since I'm relativly new it's not obvious from the docs or the lib code if I can emit a new value after the observer creation WITHOUT saving a ref to this value (as ReactiveProperty does). In other words, I'm looking for something like this:

var obs: Observable = GDRx.just(42)
obs.on_next(43) //emits a new value to subscribers

A subscriber should then receive the new 43 value.

Thank you!

**Comment by Neroware** [comment]
G'Day, this is what the Subject class is intended for. A subject is an observer and an observable at the same time, meaning you can invoke on_next() on it and use it as an observable sequence simultaneously.

Your described behavior would look like this:

var sub : Subject = Subject.new()
var obs : Observable = GDRx.merge([GDRx.just(42), sub.obs])
obs.subscribe(func(i): print("i> ", i)).dispose_with(self)
sub.on_next(43)

> First, you create a new instance of Subject. Observers can subscribe to a Subject and receive the emitted items from the observable contract (on_next, on_completed, on_error).
> You would then merge it with the observable sequence, which just emits '42'
> The third line is an example observer subscribing to 'obs'
> Finally, you can manually emit items on the resulting sequence 'obs' by calling 'on_next' on 'sub'

Please not: The README is not a full documentation, as GodotRx unfortunately does not have one yet. I do recommend reading the RxPY doc, as GodotRx is a subset of its functionality for all classes, which are outside the folder 'engine'.

**Comment by Neroware** [comment]
I will close this issue now. If you have further questions, feel free to send me an e-mail.
