### ISSUE TITLE
Problems with dispose() on RC6

### ISSUE THREAD

**Issue by TheWalruzz** [Neroware/GodotRx#3]
Again, new RC broke something in GodotRx, this time it's the `dispose()` functionality.

For instance, when `dispose()` is called by Autodisposer, an `Attempt to call function 'null::dispose (Callable)' on a null instance.` error is thrown.

I don't have time to take a deeper look into this myself at the moment, but I thought I'd let you know ;)

**Comment by Neroware** [comment]
I see. Thank you very much. Yesterday, I tested it with RC5 and was happy everything worked. I'll take a closer look at it. I guess considering GD4 we are in a hot phase right now. I hope things become more consistent from update to update when GD4 finally releases.

**Comment by Neroware** [comment]
There appears to be a change in how reference counts are handled in RC6. Observers get deleted before they are disposed causing the error...
