### ISSUE TITLE
Handling threads is solved in a convoluted and bad way

### ISSUE THREAD

**Issue by Neroware** [Neroware/GodotRx#5]
The StartableThread is a class extending the StartableBase interface. When a new thread is launched, it stores its instance in a dictionary, mapping thread ID to Thread instance and vice versa. This way, threads are managed and never die before they have finished their callback. However, wait_to_finish() is currently called in a very bad manner. A scheduler just checks in intervals, which instances have finished execution and then joins them. This is very bad for performance. A better version is already in NativeGodotRx!

**Comment by Ifhay** [comment]
Sorry but what does this mean for GodotRx users?
I see that NativeGodotRx has a few definitions that GodotRx already has — Observable, Scheduler, etc.
Should GodotRx users add NativeGodotRx GDExtension and replace all parent classes in this addon with the ones from the native one?

**Comment by Neroware** [comment]
G'Day! The simple answer: No, the native version is a separate project. The creation and joining of Godot-Threads is 
handled differently there. That is why I brought it up in the first place.

Some additional information:
- The native version has a very pretty worker thread, which is only active when Godot-Threads need to be cleaned up. This is what I want to implement in GodotRx as well instead of the naive terribleness we currently have.
- I also exaggerated a bit considering performance. I just want to free threads when they finish, not in intervals. In a bad scenario, there are many thread instances at the same time just existing without any reason between intervals.
- Also, GodotRx has not been ported to the current Godot version, so might as well add another issue there.

The faster NativeGodotRx version (already way faster than RxPY) is currently not yet public. I think you saw my abandoned repo. I still have around 60 ops to port but it will become public soon! Afterwards, I will update this version but NativeGodotRx is my current focus.

**Comment by Neroware** [comment]
Fixed with 4.1 rewrite!
